### PR TITLE
Fix for issue with Model.update() when changing column names for createdAt and updatedAt

### PR DESCRIPTION
**Pull request by aratcliffe**

### CODE REVIEW

**Comment by atiertant** [comment]
thanks for the PR but didn't pass tests, replaced by https://github.com/Atlantis-Software/offshore-schema/pull/6

**Comment by aratcliffe** [comment]
Thanks Alexandre, are you able to do a new release of offshore that uses this fix?

**Comment by atiertant** [comment]
@aratcliffe we are working on [offshore-adapter-tests](https://github.com/Atlantis-Software/offshore-adapter-tests) to add missing tests and we found many bugs... as soon as they are fixed, i'll publish a new release

**Comment by aratcliffe** [comment]
Thanks :)

**Pull request closed without merging**
